name: Docker Build & Deploy for EC2

on:
  push:
    branches:
      - 'develop'
      - 'staging'
      - 'production'
      - 'preproduction'
jobs:
  build:
    name: docker build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          fingerprint: 'C5DC716231FFE41BB7F4EC1DC031C57B48E6BDFE'

      - name: Check GPG Key
        run: |
          echo "export GPG_TTY=\$(tty)" >> ~/.profile
          echo "export GPG_TTY=\$(tty)" >> ~/.bashrc
          echo "export GPG_TTY=\$(tty)" >> ~/.bash_profile
          echo "export GPG_TTY=\$(tty)" >> ~/.zshrc
          source ~/.bashrc
          source ~/.zshrc 
          export GPG_TTY
          gpg --version

      - name: Install sops
        env:
          SOPS_VERSION: v3.7.1
        run: |
          wget https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux
          chmod +x ./sops-${SOPS_VERSION}.linux
          sudo mv ./sops-${SOPS_VERSION}.linux /usr/local/bin/sops

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate Pem
        env:
          PEM: ${{ secrets.SSH_PEM_KEY }}
        run: |
          echo -e "$PEM" > loeyb-api.pem
          chmod 400 loeyb-api.pem

      - name: Decrypt development.env, Docker build and push image to Amazon ECR and Development Deploy
        env:
          ECR: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ github.sha }}
          PEM: ${{ secrets.SSH_PEM_KEY }}
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          sops --input-type dotenv --output-type dotenv -d development.env.encrypted > development.env
          echo "== build ============================develop============================"
          docker buildx build --platform linux/amd64 --build-arg NODE_ENV=development -t ${ECR}/loeyb:latest .
          echo "== push ========================================================"
          docker push ${ECR}/loeyb --all-tags
          bash ./deploy.sh
